# Generated by Django 4.1.5 on 2023-01-06 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Additives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suggested', models.CharField(max_length=100)),
                ('lyephase', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Oils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('na_sap', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipename', models.CharField(max_length=100)),
                ('superfat', models.IntegerField()),
                ('NaOH', models.BooleanField()),
                ('lyeamount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lyeadditives', models.CharField(max_length=100)),
                ('oilname1', models.CharField(max_length=100)),
                ('oilamount1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('oilname2', models.CharField(max_length=100)),
                ('oilamount2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('oilname3', models.CharField(max_length=100)),
                ('oilamount3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('oilname4', models.CharField(max_length=100)),
                ('oilamount4', models.DecimalField(decimal_places=2, max_digits=6)),
                ('oilname5', models.CharField(max_length=100)),
                ('oilamount5', models.DecimalField(decimal_places=2, max_digits=6)),
                ('additive', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
