# Generated by Django 4.1.5 on 2023-01-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipemaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='NaOH',
        ),
        migrations.AddField(
            model_name='recipes',
            name='lyeratio',
            field=models.DecimalField(decimal_places=2, default=0.33, max_digits=6),
        ),
        migrations.AddField(
            model_name='recipes',
            name='wateramount',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
        ),
    ]
